### ISSUE TITLE
PubKey Prefixes in filters? 

### ISSUE THREAD

**Issue by vitorpamplona** [piraces/rsslay#60] opened 2023-04-23 16:13 UTC
Looks like the relay implementation doesn't return events when a prefix pubkey is used. 

From NIP-01: 
> The ids and authors lists contain lowercase hexadecimal strings, which may either be an exact 64-character match, or a prefix of the event value. A prefix match is when the filter string is an exact string prefix of the event value. The use of prefixes allows for more compact filters where a large number of values are queried, and can provide some privacy for clients that may not want to disclose the exact authors or events they are searching for.

Many clients have to use prefixed ids when the list of follows > 40 to reduce the filter size.

Let me know if you need any help understanding what needs to be done.

**Comment by piraces** [comment] 2023-04-25 17:56
Hey @vitorpamplona , thank you very much for reporting this. I didn't know about NIP-01 with prefixes but I will work in it ASAP... Will let you know via this issue when it's completed 👍

**Comment by vitorpamplona** [comment] 2023-04-25 17:58
Thank you!

**Comment by piraces** [comment] 2023-04-25 19:19
@vitorpamplona I think I have already fixed it. The problem was using an outdated version of `go-nostr`, which didn't support that partial prefixes...
I have tested it with Amethyst on Android and the issue described in your project is no longer reproducible.
Tested with Windows Subsystem for Android, following the profile (but in my instance "rsslay.nostr.moe"), closing the app and trying to force Amethyst to only send the follow list:
![image](https://user-images.githubusercontent.com/11027628/234380268-dc7ea47a-49e0-4791-a61d-b9d2d407dc83.png)

I have already published v0.4.8 of rsslay. If the user upgrades its instance to this version should be solved... Please let me know if   I am wrong or something is missing 👍

**Comment by vitorpamplona** [comment] 2023-04-25 19:23
Nice! That was fast! Thank you so much!

**Closed** 2023-04-25 19:23 UTC
Labels: bug, enhancement

**Comment by mdebus** [comment] 2023-04-25 19:41
Seems to work! Yay! Thanks a lot, @piraces !
